name: Deploy to EC2

on:
  push:
    branches:
      - main  # Despliega cuando haya push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Usar la versión de Python que necesitas

      - name: Install pipenv
        run: pip install pipenv

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}  # Usa el puerto por defecto si no se especifica
          script: |
            docker stop my-fastapi-app || true
            docker rm my-fastapi-app || true
            
            docker pull my-fastapi-app || true 

            docker run -d -p 8000:8000 --name my-fastapi-app my-fastapi-app
